import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "~/components/theme-provider";
import Header from "~/components/header";
import { Toaster } from "~/components/ui/sonner";
import { cookies } from "next/headers";
import { AppProvider } from "./appProvider";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  variable: "--font-roboto",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const token = cookieStore.get("sessionToken");
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.className} ${roboto.variable} antialiased`}>
        <ThemeProvider
          attribute={"class"}
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <AppProvider initSessionToken={token?.value}>{children}</AppProvider>
          <Toaster
            toastOptions={{
              classNames: {
                error: "!bg-red-500 text-white",
                success: "!bg-green-500 text-white",
                info: "!bg-blue-500 text-white",
              },
            }}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
